# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle from the Gradle wrapper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Verify gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Setup workspace
      uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
      with:
        args: setupDecompWorkspace

    - name: Build FAT jar
      uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
      with:
        args: build -PisFat

    - name: Build THIN jar
      uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
      with:
        args: build